addSbtPlugin("org.scalameta"             % "sbt-scalafmt"              % "2.4.6")
addSbtPlugin("com.github.cb372"          % "sbt-explicit-dependencies" % "0.2.16")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"               % "0.6.2")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"              % "0.2.2")
addSbtPlugin("com.github.sbt"            % "sbt-ci-release"            % "1.5.10")
