addSbtPlugin("org.foundweekends" % "sbt-bintray"               % "0.5.6")
addSbtPlugin("com.github.gseitz" % "sbt-release"               % "1.0.13")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"              % "2.0.0")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"               % "0.3.4")
addSbtPlugin("com.github.cb372"  % "sbt-explicit-dependencies" % "0.2.12")
