addSbtPlugin("com.github.gseitz" % "sbt-release"  % "1.0.11")
addSbtPlugin("org.foundweekends" % "sbt-bintray"  % "0.5.6")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt" % "2.0.0")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"  % "0.3.4")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.3.13" % "provided")